blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistroView


app_name = "usuarios"

urlpatterns = [
    path("login/", LoginView.as_view(template_name = "usuarios/login.html"), name = "login"),
    path("logout/", LogoutView.as_view(next_page = "../login/"), name = "logout"),
    path("registrarse/", RegistroView.as_view(), name = "registrarse")
] 

usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
    telefono = models.CharField(max_length=255) 
    domicilio = models.CharField(max_length=255, blank=True, null=True)
    es_colaborador = models.BooleanField(default=False)
    imagen_perfil = models.ImageField(upload_to = "imagenes_perfil", null=True, blank=True)
    

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario


# clase que crea un formulario

class RegistrarseForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ["first_name", "last_name", "username", "password1", "password2", "email", "telefono", "domicilio", "imagen_perfil"]

usuarios/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.edit import CreateView
from .models import Usuario
from .forms import RegistrarseForm
from django.urls import reverse
from django.contrib.auth import login


# Create your views here.

# VISTA BASADA EN CLASE QUE CREA UN USUARIO
class RegistroView(CreateView):
    model = Usuario
    template_name = "usuarios/registro.html"
    form_class = RegistrarseForm

    def get_success_url(self):
        return reverse("index")
    

    def form_valid(self, form):
        respuesta = super().form_valid(form)
        usuario = form.save()
        login(self.request, usuario)
        return respuesta

templates/usuarios/login.html
{% extends 'base.html' %}

{% load static %}


{% block contenido %}

<div class="login-container">
    <h1>Iniciar Sesion</h1>    
    <form method = "post"> {% csrf_token %}


        {{ form.as_p }}

        <button type="submit" class="custom-button">Iniciar Sesion</button>

    </form>
    <a href="{% url 'usuarios:registrarse' %}"><button class="custom-button">Crear una cuenta</button></a>
</div>

{% endblock contenido %}
    

templates/usuarios/registro.html
{% extends 'base.html' %}



{% block contenido %}
    <h1>Crea un usuario</h1>
    <form method="post"> {% csrf_token %}

        {{ form.as_p }}
        <button type="submit" class="custom-button">Crear cuenta</button>
    </form>
{% endblock contenido %}
    