blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publicaciones/urls.py
from django.urls import path, include
from publicaciones import views

app_name = 'publicaciones'


urlpatterns = [
    path('publicaciones/', views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('postear/', views.Postear.as_view(), name = 'postear'),
    path('editar-post/<int:pk>', views.EditarPost.as_view(), name = 'editar-post'),
    path('eliminar-post/<int:pk>', views.EliminarPost.as_view(), name = 'eliminar-post'),
    path('detalle-post/<int:pk>', views.PostDetalle.as_view(), name = 'detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComentarioView.as_view(), name = 'borrar-comentario')
]

publicaciones/models.py
from django.db import models
from usuarios.views import Usuario

# Create your models here.

# Esta clase crea una tabla para guardar las categorias
class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre





# Clase crea una tabla para las publicaciones
class Publicaciones(models.Model):
    fecha = models.DateField(auto_now_add = True)
    update = models.DateField(auto_now=True)
    titulo = models.CharField(max_length = 255)
    post = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, related_name='posteos', null= True)
    creador = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='posteos_usuario')

    def __str__(self):
        return self.titulo
    

class Comentario(models.Model):
    texto = models.TextField()
    fecha = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Publicaciones, on_delete = models.CASCADE, related_name = 'comentarios')
    autor = models.ForeignKey(Usuario, on_delete = models.CASCADE, related_name = 'comentarios')

    def __str__(self):
        return self.post.titulo + '--' + self.autor.first_name

publicaciones/forms.py
from django import forms
from .models import Publicaciones, Comentario


class CrearPublicacionForm(forms.ModelForm):
    class Meta:
        model = Publicaciones
        fields = ['categoria', 'titulo', 'post']
        labels = {
            'titulo': '',
            'post' : '',
            'categoria' : ''
        }

        widgets = {
            'categoria' : forms.Select(attrs={'class' : 'form-select', 'placeholder' : 'Categoria'}),
            'titulo' : forms.TextInput(attrs= {'placeholder' : 'Aca va el titulo', 'class' : 'form-control'}),
            'post' : forms.TextInput(attrs= {'placeholder' : 'Escribi algo...', 'class' : 'form-control'} )
        }
    
class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ["texto"]

publicaciones/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Publicaciones
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .forms import CrearPublicacionForm, ComentarioForm
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from core.mixins import SuperUsuarioAutorMixin, ColaboradorMixin
from publicaciones.models import Comentario
from django.core.exceptions import PermissionDenied


# Create your views here.


'''
# view basada en funcion que renderiza la pagina de publicaciones 
def publicacionesView(request):
    ctx = {
        'posteos' : Publicaciones.objects.all().order_by('fecha')
    }
    return render(request, 'publicaciones.html', ctx)
'''

# View basada en clase que renderiza las publicaciones
class VerPublicaciones(ListView):
    model = Publicaciones
    template_name = 'publicaciones/publicaciones.html'
    context_object_name = 'posteos'


    def get_queryset(self):
        consulta_anterior = super().get_queryset()
        return consulta_anterior.order_by('fecha')
    

# View que crea posteos nuevos
class Postear(ColaboradorMixin, LoginRequiredMixin, CreateView):
    model = Publicaciones
    template_name = 'publicaciones/postear.html'
    form_class = CrearPublicacionForm

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    
    def form_valid(self, form):
        f = form.save(commit=False) #le pare el carro al form para que no guarde todavia.
        f.creador_id = self.request.user.id
        return super().form_valid(f)
    


# View que actualiza una publicacion ya existente
class EditarPost(SuperUsuarioAutorMixin, LoginRequiredMixin, UpdateView):
    model = Publicaciones
    template_name = "publicaciones/editar-post.html"
    form_class = CrearPublicacionForm
    
    def get_success_url(self):
        return reverse('publicaciones:publicaciones')
    

# View que elimina un posteo
class EliminarPost(SuperUsuarioAutorMixin, LoginRequiredMixin, DeleteView):
    template_name = "publicaciones/eliminar-post.html"
    model = Publicaciones

    def get_success_url(self):
        return reverse('publicaciones:publicaciones')


class PostDetalle(DetailView):
    template_name = "publicaciones/detalle-post.html"
    model = Publicaciones
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["formulario_comentario"] = ComentarioForm()
        return context
    
    def post(self, request, *args, **kwargs):

        if not self.request.user.is_authenticated:
            return redirect("usuarios:login")
        
        publicacion = self.get_object()
        form = ComentarioForm(request.POST)

        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.autor_id = self.request.user.id
            comentario.post = publicacion
            comentario.save()
            return super().get(request)
        else:
            return super().get(request)


# View que borra comentarios
class BorrarComentarioView(SuperUsuarioAutorMixin, DeleteView):
    model = Comentario
    template_name = "publicaciones/borrar-comentario.html"

    def get_success_url(self):
        return reverse("publicaciones:detalle-post", args = [self.object.post.id])

templates/publicaciones/borrar-comentario.html
{% extends 'base.html' %}


{% block contenido %}

    <form method="post">{% csrf_token %}

        <h1>Estas a punto de borrar el comentario.</h1>
        <button type="submit" class="custom-button-danger" style="margin-left: 41%;">Eliminar</button>
        <a href="{% url 'publicaciones:publicaciones' %}" class="custom-button">Cancelar</a>

    </form>


{% endblock contenido %}
    

templates/publicaciones/detalle-post.html
{% extends 'base.html' %}
{% load static %}

{% block contenido %}
    <div class="card" style="width: 18rem;">
        <img src="{% static 'img/goku.jpg' %}" class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text">{{ post.fecha }}</p>    
          <h6>{{ post.creador }}</h6>       
          <h5 class="card-title">{{ post.titulo }}</h5>
          <p class="card-text">{{ post.post }}</p>
          <a href="#" class="btn btn-primary">OMG!!!</a>
        </div>
    </div>

    <div class="comentarios-container">
        <h2>Comentarios</h2>
        
        {% for comentarios in post.comentarios.all %}
            <div class="card">
              <div class="card-body">
                <h6>{{ comentarios.autor.first_name }} {{ comentarios.autor.last_name }}</h6>
                <p>{{ comentarios.texto }}</p>
                
                <a href="{% url 'publicaciones:borrar-comentario' comentarios.id %}">  <i class="fa-solid fa-trash"></i>  </a>
                  
              </div>
            </div>
          
        {% endfor %}
          



    </div>


    <form method="post">{% csrf_token %}
      {{ formulario_comentario }}
      <button type="submit" class="custom-button">Comentar</button>
    </form>

{% endblock contenido %}

templates/publicaciones/editar-post.html
{% extends 'base.html' %}




{% block contenido %}
    <h1>Editar posteo</h1>

        <form method="post">{% csrf_token %}


            {{ form.as_p }}
            <button type="submit" class="custom-button">Guardar cambios</button>
            <a href="{% url 'publicaciones:publicaciones' %}" class="custom-button-danger">Cancelar</a>

        </form>


{% endblock contenido %}
    

templates/publicaciones/eliminar-post.html
{% extends 'base.html' %}



{% block contenido %}
    
    <form method="post">{% csrf_token %}
        <div class="title-container" style="margin-top: 10%;">
        <h1>Estas a punto de eliminar la publicacion.</h1>
        </div>
        <div style="margin-left: 40%;">
        <h1>¿¿SEGURO??</h1>
        </div>
        <button type="submit" class="custom-button-danger" style="margin-left: 41%;">Eliminar</button>
        <a href="{% url 'publicaciones:publicaciones' %}" class="custom-button">Cancelar</a>
    </form>


{% endblock contenido %}
    

templates/publicaciones/postear.html
{% extends 'base.html' %}

{% load static %}


{% block contenido %}
    
    <h1>Empieza a publicarrr!!!</h1>
    <form method="post">{% csrf_token %}

        {{ form.as_p }}        

        <button type = "submit" class="custom-button">Publicar!</button>
        <a href="{% url 'publicaciones:publicaciones' %}" class="custom-button-danger">Cancelar</a>




    </form>

{% endblock contenido %}
    

templates/publicaciones/publicaciones.html
{% extends 'base.html' %}



{% block contenido %}

<div class="post-container">
    <h1>MIS PUBLICACIONES</h1>
    
    {% for post in posteos %}
        <div class="card m-5">
            <div class="card-header">
            {{ post.fecha }}
            </div>
            <div class="card-body">
            <h5 class="card-title">{{ post.titulo }}</h5>
            <p class="card-text">{{ post.post }}</p>
            <p class="card-text">{{ post.categoria }}</p>
            <p class="card-text">{{ post.creador }}</p>
            <a href="{% url 'publicaciones:detalle-post' post.id %}" class="custom-button">Ver más</a>


            
            {% if user.is_superuser or user == post.creador %}
            <a href="{% url 'publicaciones:editar-post' post.id %}" class="custom-button">Editar</a>
            <a href="{% url 'publicaciones:eliminar-post' post.id %}" class="custom-button-danger">Eliminar posteo</a>
            {% endif %}



            </div>
        </div>
    {% endfor %}

</div>
        
        {% if user.is_authenticated %}
        <a href="{% url 'publicaciones:postear' %}" class="custom-button" style="margin-left: 44%;">Postear algo nuevo</a>

        {% endif %}
            

{% endblock contenido %}
    