blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls"))
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

publicaciones/urls.py
from django.urls import path, include
from publicaciones import views

app_name = 'publicaciones'


urlpatterns = [
    path('publicaciones/', views.VerPublicaciones.as_view(), name = 'publicaciones'),
    path('postear/', views.Postear.as_view(), name = 'postear'),
    path('editar-post/<int:pk>', views.EditarPost.as_view(), name = 'editar-post'),
    path('eliminar-post/<int:pk>', views.EliminarPost.as_view(), name = 'eliminar-post'),
    path('detalle-post/<int:pk>', views.PostDetalle.as_view(), name = 'detalle-post'),
    path('borrar-comentario/<int:pk>', views.BorrarComentarioView.as_view(), name = 'borrar-comentario')
]

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegistroView


app_name = "usuarios"

urlpatterns = [
    path("login/", LoginView.as_view(template_name = "usuarios/login.html"), name = "login"),
    path("logout/", LogoutView.as_view(next_page = "../login/"), name = "logout"),
    path("registrarse/", RegistroView.as_view(), name = "registrarse")
] 

templates/ajustes.html
{% extends 'base.html' %}


{% block contenido %}
    <h1>CONFIGURAZAO</h1>
{% endblock contenido %}
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog nashe</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">BLOG</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'publicaciones:publicaciones' %}">Publicaciones</a>
              </li>
              <li class="nav-item dropdown">
              

              
              {% if user.is_authenticated %}

                
                {% if user.imagen_perfil %}
                <img src="{{ user.imagen_perfil.url }}" alt="imagen de perfil" class="rounded-circle" width="30" height="30">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.first_name }} 
                </a>
                
                {% else %}

                <img src="{% static 'img/spiderman.jpg' %}" alt="imagen de perfil" class="rounded-circle" width="30" height="30">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.first_name }} 
                </a>


                {% endif %}





                {% else %}


                <a class="nav-link" href="{% url 'usuarios:login' %}" role="button" aria-expanded="false">
                  Iniciar Sesion
                </a>


              {% endif %}
                

                

              
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'perfil' %}">Perfil</a></li>
                  <li><a class="dropdown-item" href="{% url 'ajustes' %}">Ajustes</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}">Cerrar sesion</a></li>
                </ul>            
              </li>
              <li class="nav-item">
                <a class="nav-link disabled"></a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
          </div>
        </div>
      </nav>
      
      {% block contenido %}
        
      {% endblock contenido %}
        

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<div class="title-container">
    <h1>EL INICIO DE TODO...</h1>
</div>
{% endblock contenido %}
    

templates/perfil.html
{% extends 'base.html' %}


{% block contenido %}
    <h1>ACA ESTÁ TU PERFIL LOCOOO</h1>
{% endblock contenido %}
    